version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: main.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
